#ifndef __INC_COMMON_
#define __INC_COMMON_
#pragma warning(disable:4786)
#pragma warning(disable:4710)
#pragma warning(disable:4702)
#include <windows.h>
#include <tchar.h>
#include <process.h>
#include <map>
#include <set>
#include <list>
#include <queue>
#include <deque>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <functional>
#include <atlbase.h>
#include <atlconv.h>
#include <strsafe.h>
#endif
